PythonProjectSet/study_projects/django_study_old/my_test/my_test/urls.py
from django.contrib import admin
from django.urls import path
# from my_site import views
from my_site.views import depart, number, user, admin

urlpatterns = [
    # path("admin/", admin.sites.urls),
    path("depart/list/", depart.depart_list),
    path("depart/add/", depart.depart_add),
    path("depart/delete/", depart.depart_delete),
    path("depart/<int:nid>/edit/", depart.depart_edit),

    path("user/list/", user.user_list),
    path("user/add/", user.user_add),
    path("user/model/form/add/", user.user_model_form_add),
    path("user/<int:nid>/edit/", user.user_edit),
    path("user/<int:nid>/delete/", user.user_delete),

    path("pretty/number/list/", number.pretty_number_list),
    path("pretty/number/add/", number.pretty_number_add),
    path("pretty/number/<int:nid>/edit/", number.pretty_number_edit),
    path("pretty/number/<int:nid>/delete/", number.pretty_number_delete),

    path("admin/list/", admin.admin_list),
    path("admin/add/", admin.admin_add),
]

PythonProjectSet/study_projects/django_study_old/my_test/my_site/models.py
from django.db import models


# Create your models here.


class Department(models.Model):
    """
    部门管理相关数据库。
    """
    title = models.CharField(max_length=32, verbose_name="标题")  # verbose_name 注解

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """
    员工管理相关数据库。
    """
    name = models.CharField(verbose_name="员工姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")
    # to：与哪张表关联 to_field: 与表中哪一个列关联
    # Django中自动做的 在底层生成数据库的列的时候 会自动生成数据列 depart_id
    depart = models.ForeignKey(to="Department", to_field="id", verbose_name="部门", on_delete=models.CASCADE)
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNumber(models.Model):
    """
    靓号管理
    """

    def __str__(self):
        return ''

    state_choices = (
        (1, "已使用"),
        (2, "未使用"),
    )
    level_choices = (
        (1, "青铜"),
        (2, "白银"),
        (3, "黄金"),
        (4, "钻石"),
        (5, "星光"),
    )
    # CharField 必须设置长度
    # 允许为空： blank=True, null=True
    mobile = models.CharField(verbose_name="号码", max_length=20)
    prices = models.IntegerField(verbose_name="价格", default=0)
    level = models.SmallIntegerField(verbose_name="等级", choices=level_choices, default=1)
    state = models.SmallIntegerField(verbose_name="状态", choices=state_choices, default=2)


class Admin(models.Model):
    """
    管理员
    """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='用户密码', max_length=64)


# END

PythonProjectSet/study_projects/django_study_old/my_test/my_site/views/admin.py
# -*- coding: utf-8 -*-
# @CreateTime : 2023/5/23 023 20:25
# @Author : 瑾瑜@20866
# @IDE : PyCharm
# @File : PycharmProject/admin.py
# @Description : 
# @Interpreter : python 3.10
# @Motto : You must take your place in the circle of life!
# @Site : https://github.com/wephiles

from django.shortcuts import render, redirect
from django import forms
from django.core.exceptions import ValidationError

from my_site import models
from my_site.utils.pagination import Pagination
from my_site.utils.bootstrap import BootStrapModelForm
from my_site.utils.encrypt import md5


def admin_list(request, ):
    """
    管理员列表
    Parameters
    ----------
    request

    Returns
    -------

    """
    # 构造搜索
    data_dict = {}
    # 如果data_dict为空，则是找到所有的
    search_data = request.GET.get('q', '')
    if search_data:
        data_dict['username__contains'] = search_data

    query_set = models.Admin.objects.filter(**data_dict)
    # 分页
    page_object = Pagination(request, query_set)
    context = {
        'queryset': query_set,
        'pagestring': page_object.html(),
        'searchdata': search_data,
    }

    return render(request, "admin_list.html", context)


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label='确认密码',
        # 输入密码的时候，显示**或者··，而不是直接显示密码原文
        widget=forms.PasswordInput(render_value=True))

    class Meta(object):
        model = models.Admin
        fields = ('username', 'password', 'confirm_password')
        # 输入密码的时候，显示**或者··，而不是直接显示密码原文

        widgets = {
            'password': forms.PasswordInput(render_value=True),
            # render_value=True表示，输入密码不一致后，不会清空密码
        }

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get('password')
        confirm = md5(self.cleaned_data.get('confirm_password'))
        if confirm != pwd:
            raise ValidationError('密码不一致')
        # return以后，会放到clean_data里面，form.save以后，会保存到数据库中！！！注意这一点
        # 返回的是什么字段，那么保存的就是什么字段
        return confirm


def admin_add(request, ):
    """
    添加管理员

    Parameters
    ----------
    request

    Returns
    -------

    """

    title = '添加管理员'
    if request.method == 'GET':
        form = AdminModelForm()
        context = {
            'title': title,
            'form': form,
        }
        # return render(request, "admin_add.html", context)
        return render(request, "change.html", context)

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'title': title, 'form': form, })
# END

PythonProjectSet/study_projects/django_study_old/my_test/my_site/views/depart.py
# -*- coding: utf-8 -*-
# @CreateTime : 2023/5/18 018 21:08
# @Author : 瑾瑜@20866
# @IDE : PyCharm
# @File : PycharmProject/depart.py
# @Description : 
# @Interpreter : python 3.10
# @Motto : You must take your place in the circle of life!
# @Site : https://github.com/wephiles

from django.shortcuts import render, redirect
from my_site import models
# from django import forms
# from django.core.validators import RegexValidator
# from django.core.validators import ValidationError
# from django.utils.safestring import mark_safe
# from datetime import datetime
from my_site.utils.pagination import Pagination
from my_site.my_forms.form import PrettyNumberEditModelForm
from my_site.my_forms.form import UserModelForm, PrettyNumberModelForm

def depart_list(request, ):
    """
    部门列表展示。

    Parameters
    ----------
    request

    Returns
    -------
    render object
    """

    # 获取部门列表
    query_set = models.Department.objects.all()

    # 分页：
    page_object = Pagination(request, query_set, page_size=2)
    context = {
        "queryset": page_object.page_query_set,
        "page_string": page_object.html(),
    }
    return render(request, 'depart_list.html', context)
    # return render(request, 'depart_list.html', {'queryset': query_set})


def depart_add(request, ):
    """
    添加部门。

    Parameters
    ----------
    request

    Returns
    -------
    render object
    """
    if request.method == 'GET':
        # 添加部门
        return render(request, "department_add.html")
    # 获取提交过来的数据 (需要判断输入为空，此处先不做判断)
    title = request.POST.get("title")
    # 保存到数据库
    models.Department.objects.create(title=title)
    # 重定向回页面
    return redirect('/depart/list/')


def depart_delete(request, ):
    """
    删除部门。

    Parameters
    ----------
    request

    Returns
    -------
    render object
    """
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect('/depart/list/')


def depart_edit(request, nid: int, ):
    """
    编辑部门。

    Parameters
    ----------
    nid
    request

    Returns
    -------
    render object
    """
    if request.method == 'GET':
        # 根据nid，获取他的数据
        row_object = models.Department.objects.filter(id=nid).first()
        # print(row_object.id, row_object.title)
        return render(request, 'depart_edit.html', {'rowobject': row_object})
    # 拿到标题
    title = request.POST.get('title')

    # 根据ID找到并更新数据
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect('/depart/list/')

# END

PythonProjectSet/study_projects/django_study_old/my_test/my_site/views/number.py
# -*- coding: utf-8 -*-
# @CreateTime : 2023/5/18 018 21:08
# @Author : 瑾瑜@20866
# @IDE : PyCharm
# @File : PycharmProject/number.py
# @Description : 
# @Interpreter : python 3.10
# @Motto : You must take your place in the circle of life!
# @Site : https://github.com/wephiles

from django.shortcuts import render, redirect
from my_site import models
# from django import forms
# from django.core.validators import RegexValidator
# from django.core.validators import ValidationError
# from django.utils.safestring import mark_safe
# from datetime import datetime
from my_site.utils.pagination import Pagination
from my_site.my_forms.form import PrettyNumberEditModelForm
from my_site.my_forms.form import UserModelForm, PrettyNumberModelForm

def pretty_number_list(request):
    """

    Parameters
    ----------
    request

    Returns
    -------

    """

    data_dict = {}
    # 如果data_dict为空，则是找到所有的
    search_data = request.GET.get('q', '')
    if search_data:
        data_dict['mobile__contains'] = search_data
    # 用自己定义的组件类实现分页
    query_set = models.PrettyNumber.objects.filter(**data_dict)
    page_object = Pagination(request, query_set)
    page_query_set = page_object.page_query_set
    page_string = page_object.html()
    context = {
        'queryset': page_query_set,  # 分完页的数据
        'search_data': search_data,
        'page_string': page_string,  # 页码
    }
    return render(request,
                  "pretty_number_list.html",
                  context)


def pretty_number_add(request, ):
    """
    添加靓号

    Parameters
    ----------
    request

    Returns
    -------

    """
    if request.method == "GET":
        form = PrettyNumberModelForm()
        return render(request, 'pretty_number_add.html', {'form': form})
    form = PrettyNumberModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/pretty/number/list/')
    return render(request, 'pretty_number_add.html', {'form': form})


def pretty_number_edit(request, nid: int):
    """
    编辑靓号

    Parameters
    ----------
    request
    nid

    Returns
    -------

    """
    row_object = models.PrettyNumber.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = PrettyNumberEditModelForm(instance=row_object)
        return render(request, 'pretty_number_edit.html', {'form': form})

    # 将修改了的信息上传到数据库，而不是新建
    form = PrettyNumberEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存的是用户输入的所有数据
        form.save()

        # 想要用户输入以外增加一些值的话
        # form.instance.字段名 = 值
        return redirect('/pretty/number/list/')
    return render(request, 'pretty_number_edit.html', {'form': form})


def pretty_number_delete(request, nid):
    models.PrettyNumber.objects.filter(id=nid).delete()
    return redirect('/pretty/number/list/')

# END

PythonProjectSet/study_projects/django_study_old/my_test/my_site/views/user.py
# -*- coding: utf-8 -*-
# @CreateTime : 2023/5/18 018 21:08
# @Author : 瑾瑜@20866
# @IDE : PyCharm
# @File : PycharmProject/user.py
# @Description : 
# @Interpreter : python 3.10
# @Motto : You must take your place in the circle of life!
# @Site : https://github.com/wephiles

from django.shortcuts import render, redirect
from my_site import models
# from django import forms
# from django.core.validators import RegexValidator
# from django.core.validators import ValidationError
# from django.utils.safestring import mark_safe
# from datetime import datetime
from my_site.utils.pagination import Pagination
from my_site.my_forms.form import PrettyNumberEditModelForm
from my_site.my_forms.form import UserModelForm, PrettyNumberModelForm

def user_list(request, ):
    """
    用户列表展示。

    Parameters
    ----------
    request

    Returns
    -------
    render object
    """

    # 获取所有用户列表
    query_set = models.UserInfo.objects.all()
    # for item in query_set:
    # print(item.id, item.age, item.name, item.create_time.strftime("%Y-%m-%d"), item.gender, item.password,
    #       item.account, item.depart_id)
    # 获得gender_choices = (
    #         (1, "男"),
    #         (2, "女"),
    #     )
    # 这种类型的数据，不只是获得简单的1 / 2
    # get_字段名_display() 如果写的是level_choices,那么就写get_level_display()

    # 此外，另外一张表通过外键关联到ID的时候，
    # depart = models.ForeignKey(to="Department", to_field="id", verbose_name="部门", on_delete=models.CASCADE)
    # 如何获取部门的值呢？直接通过item.depart.title 来获取文字， 而不是创建这一列的时候产生的ID (depart_id)

    # print(item.id, item.age, item.name, item.create_time.strftime("%Y-%m-%d"), item.get_gender_display(),
    #       item.password, item.account, item.depart.title)

    # 分页：
    page_object = Pagination(request, query_set, page_size=2)
    context = {
        "queryset": page_object.page_query_set,
        "page_string": page_object.html(),
    }
    return render(request, 'user_list.html', context)


def user_add(request, ):
    """
    添加用户（原始方式）。

    Parameters
    ----------
    request

    Returns
    -------
    render object
    """
    # if request.method == 'GET':
    #     # 添加用户
    #     return render(request, "user_add.html")
    context = {
        'genderchoices': models.UserInfo.gender_choices,
        'departlist': models.Department.objects.all(),
    }
    # 重定向回页面
    return render(request, 'user_add.html', context)


def user_model_form_add(request, ):
    """
    添加用户 —— 基于 ModelFormForm

    Parameters
    ----------
    request

    Returns
    -------

    """
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'user_model_form_add.html', {'form': form})

    # 用户post提交数据 数据校验
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        # 如果合法，保存到数据库
        form.save()
        return redirect('/user/list/')
        # print(form.cleaned_data)  # 校验成功
    else:
        # 在页面上显示错误信息
        return render(request, 'user_model_form_add.html', {'form': form})


def user_edit(request, nid: int):
    """
    编辑用户。

    Parameters
    ----------
    request

    Returns
    -------

    """

    # 根据ID获取要编辑的那一行数据(对象)
    # 自动获取所有的 row_object对象
    row_object = models.UserInfo.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = UserModelForm(instance=row_object)
        return render(request, 'user_edit.html', {'form': form})

    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存的是用户输入的所有数据
        form.save()

        # 想要用户输入以外增加一些值
        # form.instance.字段名 = 值
        return redirect('/user/list/')
    return render(request, 'user_edit.html', {'form': form})


def user_delete(request, nid: int):
    """
    删除用户。

    Parameters
    ----------
    request
    nid

    Returns
    -------

    """
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/")

# END

PythonProjectSet/study_projects/django_study_old/my_test/my_site/templates/admin_add.html
{% extends 'layout.html' %}
{% block title %}
	<title>瑾瑜-山河无恙，烟火寻常，可是你如愿的眺望？</title>
{% endblock %}

{% block content %}
	<div class="container-table">
		<div class="panel panel-default add-panel" style="margin-top: 20px;">
			<div class="panel-heading">

				<h3 class="panel-title">
					<span class="glyphicon glyphicon-repeat" aria-hidden="true" style="margin-right: 4px;"></span>
					添加管理员
				</h3>
			</div>
			<div class="panel-body">
				<div class="new">
					<div class="my-button">
						<a href="/admin/add/">
							<button type="button" class="btn btn-success">
								<i class="fa fa-plus-square-o" aria-hidden="true" style="margin-right: 3px;"></i>
								添加管理员
							</button>
						</a>
					</div>
					<div style="display: inline-block; float: right;" class="clearfix">
						<form class="navbar-form navbar-left" method="get">
							<div class="form-group">
								<label>
									<input type="text" class="form-control" name="q" placeholder="搜索"
									       value="{{ searchdata }}">
								</label>
								<button type="submit" class="btn btn-primary">
									<i class="fa fa-search" aria-hidden="true"></i>
								</button>
							</div>
						</form>
					</div>
					<div class="my-table">
						<table class="table table-hover table-bordered table-striped">
							<tbody>
							<tr>
								<th> ID</th>
								<th> 姓名</th>
								<th> 密码</th>
								<th> 操作</th>
							</tr>
							{% for item in  queryset %}
								<tr>
									<td>{{ item.id }}</td>
									<td>{{ item.username }}</td>
									<td>{{ item.password }}</td>
									<td>
										<a href="" class="btn btn-primary btn-xs">
											<i class="fa fa-pencil" aria-hidden="true"></i>
											编辑
										</a>
										<a href="" class="btn btn-danger btn-xs">
											<i class="fa fa-trash-o fa-lg"></i>
											删除
										</a>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div>
			<ul class="pagination clearfix">
				{{ pagestring }}
			</ul>
		</div>
	</div>
{% endblock %}

PythonProjectSet/study_projects/django_study_old/my_test/my_site/templates/admin_list.html
{% extends 'layout.html' %}
{% block title %}
	<title>瑾瑜-天边的月，心中的愿，你永在我身边</title>
{% endblock %}

{% block content %}
	<div class="container-table">
		<div class="panel panel-default add-panel" style="margin-top: 20px;">
			<div class="panel-heading">

				<h3 class="panel-title">
					<span class="glyphicon glyphicon-repeat" aria-hidden="true" style="margin-right: 4px;"></span>
					管理员操作
				</h3>
			</div>
			<div class="panel-body">
				<div class="new">
					<div class="my-button">
						<a href="/admin/add/">
							<button type="button" class="btn btn-success">
								<i class="fa fa-plus-square-o" aria-hidden="true" style="margin-right: 3px;"></i>
								添加管理员
							</button>
						</a>
					</div>
					<div style="display: inline-block; float: right;" class="clearfix">
						<form class="navbar-form navbar-left" method="get">
							<div class="form-group">
								<label>
									<input type="text" class="form-control" name="q" placeholder="搜索"
									       value="{{ searchdata }}">
								</label>
								<button type="submit" class="btn btn-primary">
									<i class="fa fa-search" aria-hidden="true"></i>
								</button>
							</div>
						</form>
					</div>
					<div class="my-table">
						<table class="table table-hover table-bordered table-striped">
							<tbody>
							<tr>
								<th> ID</th>
								<th> 姓名</th>
								<th> 密码</th>
								<th> 操作</th>
							</tr>
							{% for item in  queryset %}
								<tr>
									<td>{{ item.id }}</td>
									<td>{{ item.username }}</td>
									<td>{{ item.password }}</td>
									<td>
										<a href="" class="btn btn-primary btn-xs">
											<i class="fa fa-pencil" aria-hidden="true"></i>
											编辑
										</a>
										<a href="" class="btn btn-danger btn-xs">
											<i class="fa fa-trash-o fa-lg"></i>
											删除
										</a>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div>
			<ul class="pagination clearfix">
				{{ pagestring }}
			</ul>
		</div>
	</div>
{% endblock %}

PythonProjectSet/study_projects/django_study_old/my_test/my_site/templates/depart_edit.html
{% extends 'layout.html' %}

{% block title %}
	<title>瑾瑜-山河无恙，烟火寻常，可是你如愿的眺望。</title>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="panel panel-default" style="margin-top: 10px;">
			<div class="panel-heading">
				<h3 class="panel-title">
{#					<button type="button" class="btn btn-success">#}
						<i class="fa fa-edit" aria-hidden="true"></i>
						修改部门
{#					</button>#}
				</h3>
			</div>
			<div class="panel-body">
				<form action="" method="post">
					<div class="form-group">
						{% csrf_token %}
						<label style="margin-left: 4px;">标题</label>
						<input type="text" class="form-control" value="{{ rowobject.title }}" name="title">
						{#					value属性：默认值#}
					</div>
					<button type="submit" class="btn btn-primary">提交</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

PythonProjectSet/study_projects/django_study_old/my_test/my_site/templates/depart_list.html
{% extends 'layout.html' %}

{% block title %}
	<title>瑾瑜-孩子们啊，安睡梦乡，像你深爱的那样。</title>
{% endblock %}

{% block content %}

	<div class="container-table">
		<div class="panel panel-default add-panel" style="margin-top: 20px;">
			<div class="panel-heading">

				<h3 class="panel-title">
					<span class="glyphicon glyphicon-repeat" aria-hidden="true" style="margin-right: 4px;"></span>
					部门操作
				</h3>
			</div>
			<div class="panel-body">
				<div class="new">
					<div class="my-button">
						<a href="/depart/add/">
							<button type="button" class="btn btn-success">
								<i class="fa fa-plus-square-o" aria-hidden="true" style="margin-right: 3px;"></i>
								新建部门
							</button>
						</a>
					</div>
					<div style="margin-bottom: 10px; margin-top: 10px;">
					<span class="glyphicon glyphicon-th" aria-hidden="true"
					      style="margin-left: 10px; margin-right: 5px;"></span>
						部门列表
					</div>
					<div class="my-table">
						<table class="table table-hover table-bordered table-striped">
							<tbody>
							<tr>
								<th>#</th>
								<th>部门名称</th>
								{#							<th>表头2</th>#}
								<th>操作</th>
							</tr>
							{% for item in  queryset %}
								<tr>
									<td>{{ item.id }}</td>
									<td>{{ item.title }}</td>
									<td>
										<a href="/depart/{{ item.id }}/edit/" class="btn btn-primary btn-xs">
											<i class="fa fa-pencil" aria-hidden="true"></i>
											编辑
										</a>
										<a href="/depart/delete/?nid={{ item.id }}" class="btn btn-danger btn-xs">
											<i class="fa fa-trash-o fa-lg"></i>
											删除
										</a>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div>
			<ul class="pagination clearfix">
				{{ page_string }}
			</ul>
		</div>
	</div>

{% endblock %}

PythonProjectSet/study_projects/django_study_old/my_test/my_site/templates/pretty_number_list.html
{% extends 'layout.html' %}

{% block title %}
	<title>瑾瑜-这世界有那么多人，多幸运，我有个我们。</title>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="panel panel-primary" style="margin-top: 10px;">
			<div class="panel-heading">
				<i class="fa fa-mobile-phone" aria-hidden="true" style="font-size: 20px;"></i>
				<span style="margin-left: 8px; font-size: 20px;">靓号管理</span>
			</div>
			<div class="panel-body">
				<div>
					<div class="my-button">
						<a href="/pretty/number/add/">
							<button type="button" class="btn btn-success">
								<i class="fa fa-plus-square-o" aria-hidden="true" style="margin-right: 3px;"></i>
								添加靓号
							</button>
						</a>
					</div>
					<div style="display: inline-block; float: right;" class="clearfix">
						<form class="navbar-form navbar-left" method="get">
							<div class="form-group">
								<label>
									<input type="text" class="form-control" name="q" placeholder="搜索号码"
									       value="{{ search_data }}">
								</label>
								<button type="submit" class="btn btn-primary">
									<i class="fa fa-search" aria-hidden="true"></i>
								</button>
							</div>
						</form>
					</div>
					<div class="panel panel-default" style="margin-left: 10px; margin-top: 10px;">
						<div class="panel-heading" style="">所有靓号</div>
						<table class="table table-bordered table-hover table-striped">
							<thead>
							<tr>
								<th>ID</th>
								<th>电话号码</th>
								<th>靓号等级</th>
								<th>靓号状态</th>
								<th>靓号价格</th>
							</tr>
							</thead>
							<tbody>
							{% for item in queryset %}
								<tr>
									<th scope="row">{{ item.id }}</th>
									<td>{{ item.mobile }}</td>
									<td>{{ item.prices }}</td>
									<td>{{ item.get_level_display }}</td>
									<td>{{ item.get_state_display }}</td>
									<td>
										<a href="/pretty/number/{{ item.id }}/edit/" class="btn btn-primary btn-xs">
											<i class="fa fa-pencil" aria-hidden="true"></i>
											编辑
										</a>
										<a href="/pretty/number/{{ item.id }}/delete/" class="btn btn-danger btn-xs">
											<i class="fa fa-trash-o fa-lg"></i>
											删除
										</a>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<div>
					<ul class="pagination clearfix">
						{{ page_string }}
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

PythonProjectSet/study_projects/django_study_old/my_test/my_site/templates/user_model_form_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet"
	      href="{% static 'plugins/bootstrap-datepicker-1.6.4-dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block title %}
	<title>瑾瑜-这世界有那么多人，人群里，敞着一扇门</title>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="panel panel-default" style="margin-top: 10px;">
			<div class="panel-heading">
				<h3 class="panel-title">
					添加用户
				</h3>
			</div>
			<div class="panel-body">
				<form method="post" novalidate>
					{% for field in form %}
						<div class="form-group">
							{% csrf_token %}
							<label style="margin-left: 4px;">{{ field.label }}</label>
							{{ field }}
							<!-- 错误信息 是个列表 -->
							<span style="color: red;">{{ field.errors.0 }}</span>
						</div>
					{% endfor %}
					<button type="submit" class="btn btn-primary">提交</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block js %}
	<script src="{% static '/plugins/bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.min.js' %}"></script>
	<script src="{% static '/plugins/bootstrap-datepicker-1.6.4-dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
	<script type="text/javascript">
        $(function () {
            $("#id_create_time").datepicker({
                format: "yyyy-mm-dd",
                {#startDate: "0",#}
                {#startDate: new Date(),#}
                language: "zh-CN",
                autoclose: true,
                clearBtn: true,
                todayHighlight: true
            })
        })
	</script>
{% endblock %}